//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvestustoo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arvestustoo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active language.
        /// </summary>
        internal static string AktiivneKeel {
            get {
                return ResourceManager.GetString("AktiivneKeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Movies.
        /// </summary>
        internal static string FilmidPealkiri {
            get {
                return ResourceManager.GetString("FilmidPealkiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string FilmiMarkused {
            get {
                return ResourceManager.GetString("FilmiMarkused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie name.
        /// </summary>
        internal static string FilmiNimi {
            get {
                return ResourceManager.GetString("FilmiNimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster URL.
        /// </summary>
        internal static string FilmiPildiUrl {
            get {
                return ResourceManager.GetString("FilmiPildiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string FilmiZanr {
            get {
                return ResourceManager.GetString("FilmiZanr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        internal static string HeleTeema {
            get {
                return ResourceManager.GetString("HeleTeema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound effects.
        /// </summary>
        internal static string HeliSeaded {
            get {
                return ResourceManager.GetString("HeliSeaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string HinneLabel {
            get {
                return ResourceManager.GetString("HinneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string KustutaNupp {
            get {
                return ResourceManager.GetString("KustutaNupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Movie.
        /// </summary>
        internal static string LisaFilmPealkiri {
            get {
                return ResourceManager.GetString("LisaFilmPealkiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string LisaNupp {
            get {
                return ResourceManager.GetString("LisaNupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string MarkusedLabel {
            get {
                return ResourceManager.GetString("MarkusedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MuudaNupp {
            get {
                return ResourceManager.GetString("MuudaNupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string MuutmineRezim {
            get {
                return ResourceManager.GetString("MuutmineRezim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movies yet. Add your first one!.
        /// </summary>
        internal static string OnTyhi {
            get {
                return ResourceManager.GetString("OnTyhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SalvestaNupp {
            get {
                return ResourceManager.GetString("SalvestaNupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SeadedPealkiri {
            get {
                return ResourceManager.GetString("SeadedPealkiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string TumeTeema {
            get {
                return ResourceManager.GetString("TumeTeema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string TyhjendaNupp {
            get {
                return ResourceManager.GetString("TyhjendaNupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string ZanrLabel {
            get {
                return ResourceManager.GetString("ZanrLabel", resourceCulture);
            }
        }
    }
}
