//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Naidis_TARpe24 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Naidis_TARpe24.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiivne keel.
        /// </summary>
        public static string AktiivneKeel {
            get {
                return ResourceManager.GetString("AktiivneKeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avasta Tallinn.
        /// </summary>
        public static string AvastaPealkiri {
            get {
                return ResourceManager.GetString("AvastaPealkiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eemalda.
        /// </summary>
        public static string Eemalda {
            get {
                return ResourceManager.GetString("Eemalda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juba lemmikutes!.
        /// </summary>
        public static string JubaLemmik {
            get {
                return ResourceManager.GetString("JubaLemmik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Estonian.
        /// </summary>
        public static string KeeleNupp {
            get {
                return ResourceManager.GetString("KeeleNupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali keel:.
        /// </summary>
        public static string KeelValik {
            get {
                return ResourceManager.GetString("KeelValik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemmikuks lisatud!.
        /// </summary>
        public static string LemmikLisatud {
            get {
                return ResourceManager.GetString("LemmikLisatud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minu lemmikud.
        /// </summary>
        public static string LemmikudPealkiri {
            get {
                return ResourceManager.GetString("LemmikudPealkiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemmikuid pole veel. Vajuta kaardile, et lisada!.
        /// </summary>
        public static string LemmikudTyhi {
            get {
                return ResourceManager.GetString("LemmikudTyhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa lemmikutesse.
        /// </summary>
        public static string LisaLemmik {
            get {
                return ResourceManager.GetString("LisaLemmik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string LoodudPrefix {
            get {
                return ResourceManager.GetString("LoodudPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Languages.
        /// </summary>
        public static string Pealkiri {
            get {
                return ResourceManager.GetString("Pealkiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaded.
        /// </summary>
        public static string SeadedPealkiri {
            get {
                return ResourceManager.GetString("SeadedPealkiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulge.
        /// </summary>
        public static string Sulge {
            get {
                return ResourceManager.GetString("Sulge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tühista.
        /// </summary>
        public static string Tyhista {
            get {
                return ResourceManager.GetString("Tyhista", resourceCulture);
            }
        }
    }
}
